# Project information
site_name: Pytorch_basics
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Section 1 PyTorch Introduction: Section_001_PyTorch_Introduction.md
  - Section 2 PyTorch Tensors and Operations: Section_002_PyTorch_Tensors_and_Operations.md
  - Section 3 AutoGrad: Section_003_AutoGrad.md
  - Section 4 First Neural Network: Section_004_PyTorch_First_NN.md
  - Section 5 Custom data loading: Section_005_Custom_data_loading.md
  - Section 6 Convolutional Neural Network: Section_006_CNN.md
  - Section 7 Transfer learning: Section_007_Transfer_learning.md
  - References: references.md
site_author: Sushant Sur
site_description: >-
  DESCRIPTION

# Repository
repo_name: sushantsur23/Pytorch-basics
repo_url: https://github.com/sushantsur23/Pytorch-basics

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: teal
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: teal
      accent: lime    
  # logo: PyTorch_logo_icon.svg
  
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/sushantsur23
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sushantsur23
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/sushantsur23
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/sushantsur23/

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2022 <a href="https://github.com/sushantsur23"  target="_blank" rel="noopener">Sushant Sur</a>